[package]
name = "ysos_dinner"
version = "0.1.0"
edition = "2021"
[workspace]
[dependencies]
lib = { path="../../lib", package="yslib"}
rand = { version = "0.8", default-features = false }
rand_chacha = { version = "0.3", default-features = false }
